baseURL: "https://nicktackes.com/"
languageCode: en-us
title: Nick Tackes

Params:
  sidebar:
    alt: "Photograph of the author"
    menu: ["about", "research", "teaching", "cv"]
    landing: "about"

  social:
    - URL: mailto:jtackes@hamilton.edu
      icon: fas fa-envelope fa-lg
      label: email
    - URL: https://columbia.academia.edu/NickTackes/
      icon: ai ai-academia fa-lg
      label: academia.edu
    - URL: https://github.com/jtackesiii
      icon: fab fa-github fa-lg
      label: github
    - URL: https://linkedin.com/in/NickTackes
      icon: fab fa-linkedin fa-lg
      label: linkedin

  credits:
    This site is built on [Hugo](https://gohugo.io),
     hosted on [Github](https://github.com), and
    served on [Netlify](https://netlify.com). Icons
    are by [Fontawesome](https://fontawesome.com) and
    [Academicons](https://jpswalsh.github.io/academicons).
